### PR TITLE
Tc001 aisha 

### PR DESCRIPTION
**Pull request by AishaAydin**
lets code I added

### CODE REVIEW

**Comment by orazovalibek** [comment]
Great job Aisha ! and can you please add print statement that says : " have a great day "

**Comment by orazovalibek** [comment]
Great job Aisha ! and can you please add print statement that says : " have a great day "

**Review by orazovalibek — COMMENTED** [review]
Great job Aisha ! and can you please add print statement that says : " have a great day "

**Review by RitaFurman — COMMENTED** [review]
looks perfect

**Review by Elif-Cybertek — APPROVED** [review]
very good Aisha, I agree with 3rd line codes ))

**Comment by AishaAydin** [comment]
Thank you guys!! you are very supportive :)

**Pull request merged**
